# Generated by Django 5.1.7 on 2025-03-24 06:49

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intro_econ', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='econarticle',
            name='content',
            field=markdownx.models.MarkdownxField(verbose_name='記事内容 (Markdown)'),
        ),
    ]
