# Generated by Django 5.1.7 on 2025-03-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('biography', models.TextField()),
                ('specialty', models.CharField(max_length=200)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='prof_images/')),
                ('message', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
